-- AlterTable
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "annualRetirementTarget" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "netZeroTarget" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "netZeroTargetYear" INTEGER;
