-- AlterTable Credit: add columns present in schema but missing from init migration
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "methodology" TEXT;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "standard" TEXT;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "sdgs" TEXT;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "vintageYear" INTEGER;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "price" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "searchVector" TEXT;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "featuredUntil" TIMESTAMP(3);
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "viewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "purchaseCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Credit" ADD COLUMN IF NOT EXISTS "lastPurchasedAt" TIMESTAMP(3);
